config/routes.rb
Rails.application.routes.draw do
  root 'users#new'  # Root URL for user email input
  get '/login', to: 'sessions#new'  # Admin login page
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'
   get 'backlinks/by_country', to: 'backlinks#by_country', as: 'backlinks_by_country'
   get 'backlinks/by_category', to: 'backlinks#by_category', as: 'backlinks_by_category'
   get 'backlinks/by_new', to: 'backlinks#by_new', as: 'backlinks_by_new'
     get 'backlinks/by_special', to: 'backlinks#by_special', as: 'backlinks_by_special'
     get 'backlinks/recently_deleted', to: 'backlinks#recently_deleted', as: 'backlinks_recently_deleted'
  
  get '/admin/dashboard', to: 'admin#dashboard'  # Admin dashboard
  get 'backlinks/home', to: 'backlinks#home'

  resources :backlinks
  resources :users
end

app/models/backlink.rb
class Backlink < ApplicationRecord
	validates :site, :country, :category, :price, :domain_rank, :added_on, :duration, presence: true
end

app/controllers/backlinks_controller.rb
class BacklinksController < ApplicationController
  before_action :set_backlink, only: %i[ show edit update destroy ]
  before_action :hide_cat_col
 

def require_admin
  unless session[:admin]
    redirect_to login_path, alert: "You must be logged in as admin to perform this action"
  end
end

  # GET /backlinks or /backlinks.json
  def index
  @backlinks = Backlink.all
  @category_colors = assign_colors(@backlinks.pluck(:category).uniq.compact)
  # Filtering by country
    if params[:country].present?
      @backlinks = @backlinks.where(country: params[:country])
    end

    # Filtering by category
    if params[:category].present?
      @backlinks = @backlinks.where(category: params[:category])
    end

    # Filtering by price range
    if params[:min_price].present?
      @backlinks = @backlinks.where('price >= ?', params[:min_price].to_i)
    end

    if params[:max_price].present?
      @backlinks = @backlinks.where('price <= ?', params[:max_price].to_i)
    end

    # Filtering by article writing (boolean)
    if params[:article_writing].present?
      @backlinks = @backlinks.where(article_writing: params[:article_writing] == 'true')
    end

    # Filtering by CS possible (boolean)
    if params[:cs_possible].present?
      @backlinks = @backlinks.where(cs_possible: params[:cs_possible] == 'true')
    end

    # Filtering by special price (boolean)
    if params[:special_price].present?
      @backlinks = @backlinks.where(special_price: params[:special_price] == 'true')
    end
  # Add more filters as needed
end
  # GET /backlinks/1 or /backlinks/1.json
  def show
  end

  # GET /backlinks/new
  def new
    @backlink = Backlink.new
  end

  # GET /backlinks/1/edit
  def edit
  end

  # POST /backlinks or /backlinks.json
  def create
    @backlink = Backlink.new(backlink_params)

    respond_to do |format|
      if @backlink.save
        format.html { redirect_to new_backlink_url, notice: "Backlink was successfully created." }
        format.json { render :show, status: :created, location: @backlink }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @backlink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backlinks/1 or /backlinks/1.json
  def update
    respond_to do |format|
      if @backlink.update(backlink_params)
        format.html { redirect_to admin_dashboard_path, notice: "Backlink was successfully updated." }
        format.json { render :admin_dashboard, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @backlink.errors, status: :unprocessable_entity }
      end
    end
  end

   def home
    @backlinks_by_country = Backlink.all.group_by(&:country)
  end


  # DELETE /backlinks/1 or /backlinks/1.json
  def destroy
    @backlink.destroy

    respond_to do |format|
      format.html { redirect_to backlinks_url, notice: "Backlink was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def by_country
    # Find backlinks based on the selected country passed as a parameter

    if params[:country].present?
      @backlinks = Backlink.where(country: params[:country])
       @category_colors = assign_colors(@backlinks.pluck(:category).uniq.compact)
    else
      @backlinks = Backlink.all # Fallback to all backlinks if no country is selected
       @category_colors = assign_colors(@backlinks.pluck(:category).uniq.compact)
    end
  end

   def by_new
    # Calculate the date range for the last 4 months
    four_months_ago = 4.months.ago.to_date

    # If the :country param is provided, filter by country and the added_on date
    if params[:country].present?
      @backlinks = Backlink.where('added_on >= ?', four_months_ago)
                           .where(country: params[:country])
                           .order(added_on: :desc)
                            @category_colors = assign_colors(@backlinks.pluck(:category).uniq.compact)
    else
      # If no country is provided, just filter by the added_on date
      @backlinks = Backlink.where('added_on >= ?', four_months_ago)
                           .order(added_on: :desc)
                            @category_colors = assign_colors(@backlinks.pluck(:category).uniq.compact)
    end
  end


  def by_special
    # Find backlinks based on the selected country passed as a parameter
    if params[:country].present?
      @backlinks = Backlink.where(special_price: true)
                           .where(country: params[:country])
                           .order(added_on: :desc)
                            @category_colors = assign_colors(@backlinks.pluck(:category).uniq.compact)
    else
      # If no country is provided, just filter by the added_on date
      @backlinks = Backlink.where(special_price: true)
                           .order(added_on: :desc)
                            @category_colors = assign_colors(@backlinks.pluck(:category).uniq.compact)
    end
  end


  def by_category
    # Find backlinks based on the selected country passed as a parameter
    if params[:category].present?
      @backlinks = Backlink.where(category: params[:category])
       @category_colors = assign_colors(@backlinks.pluck(:category).uniq.compact)
       @hide_col = true
    else
      @backlinks = Backlink.all # Fallback to all backlinks if no country is selecte
       @category_colors = assign_colors(@backlinks.pluck(:category).uniq.compact)
    end
  end

  def recently_deleted
   @backlinks = Backlink.where(available: false).order(updated_at: :desc)
  end


  private

   def set_backlink
    @backlink = Backlink.find(params[:id])
  end

  def backlink_params
    params.require(:backlink).permit(:added_on, :country, :site, :price, :traffic, :domain_rank, :category, :duration, :article_writing, :cs_possible, :special_price, :comments)
  end

  def assign_colors(categories)
    colors = [
      "#264653", "#2A9D8F", "#E76F51", "#1D3557", "#457B9D",
      "#2B2D42", "#8D99AE", "#D90429", "#3A0CA3", "#7209B7",
      "#3F37C9", "#4A4E69", "#22223B", "#9A031E", "#5A189A",
      "#023047", "#FF006E", "#3A506B", "#1B263B", "#0D3B66",
      "#144552", "#003566", "#001D3D", "#004B23", "#2D6A4F",
      "#606C38", "#283618", "#102027", "#232931", "#393E46"
    ]

    # Create a hash with categories as keys and colors as values
    categories.each_with_index.with_object({}) do |(category, index), hash|
      hash[category] = colors[index % colors.length]
    end
  end
  def hide_cat_col
    @hide_col = false
  end
end

app/helpers/backlinks_helper.rb
module BacklinksHelper
end

app/views/backlinks/_backlink.html.erb
<div id="<%= dom_id backlink %>">
</div>

app/views/backlinks/_form.html.erb
<%= form_with(model: backlink) do |form| %>
  <% if backlink.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(backlink.errors.count, "error") %> prohibited this backlink from being saved:</h2>

      <ul>
        <% backlink.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/backlinks/by_category.html.erb
<h1>Links for <%= params[:category] %></h1>

<% if @backlinks.present? %>
  <%= render 'backlinks/link_table' %>
 <% else %>
  <p>No backlinks found for <%= params[:category] %>.</p>
<% end %>

app/views/backlinks/by_country.html.erb
<h1>Links for <%= params[:country] %></h1>

<% if @backlinks.present? %>
  <%= render 'backlinks/link_table' %>
<% else %>
  <p>No backlinks found for <%= params[:country] %>.</p>
<% end %>

app/views/backlinks/by_new.html.erb
<h1>Recently Added <%= params[:country] || '' %></h1>

<% if @backlinks.any? %>
 <%= render 'backlinks/link_table' %>
<% else %>
  <p>No new backlinks found for <%= params[:country] || 'all countries' %>.</p>
<% end %>

app/views/backlinks/by_special.html.erb
<h1>Special Prices <%= params[:country] || '' %></h1>

<% if @backlinks.any? %>
 <%= render 'backlinks/link_table' %>
<% else %>
  <p>No new backlinks found for <%= params[:country] || 'all countries' %>.</p>
<% end %>

app/views/backlinks/edit.html.erb
<h1>Editing backlink</h1>

<%= render "form", backlink: @backlink %>

<br>

<div>
  <%= link_to "Show this backlink", @backlink %> |
  <%= link_to "Back to backlinks", backlinks_path %>
</div>

app/views/backlinks/home.html.erb
<div class="row row-cols-1 row-cols-lg-3 row-cols-xxl-3">
          <div class="col">
            
          </div>
          
        </div>
<% @backlinks_by_country.each do |country, backlinks| %>
      
  <div class="card radius-10 w-100">
          <div class="card-body">
            <div class="d-flex align-items-center" style="margin-bottom: 10px;">

              <%= image_tag country + ".png", class: "flag" %><h2 class="country-title mb-0"><%= country %></h3>
          
            </div>
            <div class= "row" >
            <div class="col-md-4">
            <div class="table-responsive mt-2 radius-10 mini-table">
              <table class="table align-middle mb-0 lz-bg-table">
                <thead class="table-light" style="background:#D9EDF1;">
                  <tr>
                    <th class="table-title-home">New</th>
                    
                     <th colspan="2"style="text-align: right; background:#EDF7F9;" class="lz-bg-table"> <%= link_to "View More", backlinks_by_new_path(country: country), class: 'btn btn-light view-more-btn' %></th>
                      
                  </tr>
                </thead>
                <tbody>
                  <% backlinks.compact.select { |b| b.added_on.present? }.sort_by(&:added_on).last(5).each do |backlink| %>
                      <tr class="text-secondary small">
                    <td><%=backlink.added_on %></td>
                    <td ><%= clean_url(backlink.site) %></td>
                  
          
                    <td>
                      <div class="d-flex align-items-center gap-3 fs-6">
                        <a href="javascript:;" class="text-primary view-backlink"
                           data-bs-toggle="modal" 
                data-bs-target="#backlinkModal"
                data-site="<%= backlink.site %>"
                data-price="<%= backlink.price %>"
                data-domain-rank="<%= backlink.domain_rank %>"
                data-category="<%= backlink.category %>"
                data-duration="<%= backlink.duration %>"
                data-article-writing="<%= backlink.article_writing %>"
                data-cs-possible="<%= backlink.cs_possible %>"
                data-comments="<%= backlink.comments %>"
                data-special-price="<%= backlink.special_price %>"
                data-available="<%= backlink.available %>">
                            <ion-icon class="view-backlink" name="eye-outline"></ion-icon>
                          </a>
                      </div>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            </div>
            <div class="col-md-4">
            <div class="table-responsive mt-2 radius-10 mini-table">
              <table class="table align-middle mb-0">
                <thead class="table-light">
                  <tr>
                    <th class="table-title-home">Special Price</th>
                    
                     <th colspan="2"style="text-align: right; background:#EDF7F9;" > <%= link_to "View More", backlinks_by_special_path(country: country), class: 'btn btn-light view-more-btn' %></th>
          
                  </tr>
                </thead>
                <tbody>
                  <% backlinks.select { |b| b.special_price }.sort_by(&:added_on).last(5).each do |backlink| %>
                      <tr class="text-secondary small">
                        
                    
                    <td><%= clean_url(backlink.site) %></td>
                    <td>  &#8364;<%= backlink.price %></td>
                    <td>
                      <div class="d-flex align-items-center gap-3 fs-6">
                        <a href="javascript:;" class="text-primary view-backlink"
                                       data-bs-toggle="modal" 
                            data-bs-target="#backlinkModal"
                            data-site="<%= backlink.site %>"
                            data-price="<%= backlink.price %>"
                            data-domain-rank="<%= backlink.domain_rank %>"
                            data-category="<%= backlink.category %>"
                            data-duration="<%= backlink.duration %>"
                            data-article-writing="<%= backlink.article_writing %>"
                            data-cs-possible="<%= backlink.cs_possible %>"
                            data-comments="<%= backlink.comments %>"
                            data-special-price="<%= backlink.special_price %>"
                            data-available="<%= backlink.available %>">
                            <ion-icon name="eye-outline"></ion-icon>
                          </a>
                      </div>
                    </td>
                  </tr>
                    <% end %>
                </tbody>
              </table>
            </div>
            </div>
            <div class="col-md-4">
            <div class="table-responsive mt-2 radius-10 mini-table">
              <table class="table align-middle mb-0">
                <thead class="table-light">
                  <tr>
                    <th class="table-title-home">Top Ranking</th>
                     <th colspan="2"style="text-align: right; background:#EDF7F9;" ><button class="btn btn-light view-more-btn" >View More</button></th>
                  </tr>
                </thead>
                <tbody>
                  <% backlinks.sort_by(&:domain_rank).last(5).reverse.each do |backlink| %>
                      <tr class="text-secondary small">
                        
                    <td><%= clean_url(backlink.site) %></td>
                    <td><%= backlink.domain_rank %></td>
                  
                    <td>
                      <div class="d-flex align-items-center gap-3 fs-6">
                        <a href="javascript:;" class="text-primary view-backlink"
                                    data-bs-toggle="modal" 
                            data-bs-target="#backlinkModal"
                            data-site="<%= backlink.site %>"
                            data-price="<%= backlink.price %>"
                            data-domain-rank="<%= backlink.domain_rank %>"
                            data-category="<%= backlink.category %>"
                            data-duration="<%= backlink.duration %>"
                            data-article-writing="<%= backlink.article_writing %>"
                            data-cs-possible="<%= backlink.cs_possible %>"
                            data-comments="<%= backlink.comments %>"
                            data-special-price="<%= backlink.special_price %>"
                            data-available="<%= backlink.available %>">
                            <ion-icon name="eye-outline"></ion-icon>
                          </a>
                      </div>
                    </td>
                  </tr>
                    <% end %>
                </tbody>
              </table>
            </div>
            </div>
          </div>
        </div>
        <div class="card-footer" style="text-align: right;">
          
                <th colspan="2"style="text-align: right"> <%= link_to "View All " + country + " ("+ Backlink.where(country: country).count.to_s + " links)", backlinks_by_country_path(country: country), class: 'btn btn-primary core-btn' %></th>
        </div>
      </div>

    <% end %>

    <div class="modal fade" id="backlinkModal" tabindex="-1" aria-labelledby="backlinkModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg"> <!-- Added modal-lg class for larger size -->
    <div class="modal-content" style="border-radius: 20px;">
      <div class="modal-header" style="background-color: #1A1364; color: white; border-top-left-radius: 20px; border-top-right-radius: 20px; display: flex; align-items: center; justify-content: space-between;">
        <div style="display: flex; align-items: center;">
            <%= image_tag 'linkzenit.png', style:"margin-right:20px; max-width:80px;"%>
          <h5 class="modal-title" id="backlinkModalLabel" style="margin-right: 10px;">Backlink Details</h5>
          <!-- Image space added here -->
        
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="color: white;"></button>
      </div>
      <div class="modal-body" style="padding: 20px;">
        <div class="row mb-2">
          <div class="col-6"><strong>Site:</strong></div>
          <div class="col-6" id="modal-site"></div>
        </div>
        <div class="row mb-2">
          <div class="col-6"><strong>Price:</strong></div>
          <div class="col-6">
            &#8364;<span id="modal-price"></span>
            <span id="special-price-badge" class="badge bg-warning text-dark" style="display: none;">Special Price</span>
          </div>
        </div>
        <div class="row mb-2">
          <div class="col-6"><strong>Domain Rank:</strong></div>
          <div class="col-6" id="modal-domain-rank"></div>
        </div>
        <div class="row mb-2">
          <div class="col-6"><strong>Category:</strong></div>
          <div class="col-6" id="modal-category"></div>
        </div>
        <div class="row mb-2">
          <div class="col-6"><strong>Duration:</strong></div>
          <div class="col-6" id="modal-duration"></div>
        </div>
        <div class="row mb-2">
          <div class="col-6"><strong>Article Writing:</strong></div>
          <div class="col-6" id="modal-article-writing"></div>
        </div>
        <div class="row mb-2">
          <div class="col-6"><strong>CS Possible:</strong></div>
          <div class="col-6" id="modal-cs-possible"></div>
        </div>
        <div id="comments-section" class="row mb-2" style="display: none;">
          <div class="col-6"><strong>Additional Comments:</strong></div>
          <div class="col-6" id="modal-comments"></div>
        </div>
      </div>
      <div class="modal-footer" style="border-top: 1px solid #e9ecef;">
         <button class="btn btn-outline-primary contact-btn">Enquire</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="border-radius: 20px;">Close</button>
      </div>
    </div>
  </div>
</div>

    <script>
      document.addEventListener('DOMContentLoaded', function () {
  // Attach click event listener to all "eye" icons
  document.querySelectorAll('.view-backlink').forEach(function (button) {
    button.addEventListener('click', function () {
      // Fetch data attributes from the clicked button
      const site = button.getAttribute('data-site') || 'N/A';
      const price = button.getAttribute('data-price') || 'N/A';
      const domainRank = button.getAttribute('data-domain-rank') || 'N/A';
      const category = button.getAttribute('data-category') || 'N/A';
      const duration = button.getAttribute('data-duration') || 'N/A';
      const articleWriting = button.getAttribute('data-article-writing') === 'true' ? 'Yes' : 'No';
      const csPossible = button.getAttribute('data-cs-possible') === 'true' ? 'Yes' : 'No';
      const comments = button.getAttribute('data-comments');
      const specialPrice = button.getAttribute('data-special-price') === 'true';

      // Populate the modal fields with the fetched data
      document.getElementById('modal-site').textContent = site;
      document.getElementById('modal-price').textContent = price;
      document.getElementById('modal-domain-rank').textContent = domainRank;
      document.getElementById('modal-category').textContent = category;
      document.getElementById('modal-duration').textContent = duration;
      document.getElementById('modal-article-writing').textContent = articleWriting;
      document.getElementById('modal-cs-possible').textContent = csPossible;

      // Show special price badge if applicable
      const specialPriceBadge = document.getElementById('special-price-badge');
      if (specialPrice) {
        specialPriceBadge.style.display = 'inline';
      } else {
        specialPriceBadge.style.display = 'none';
      }

      // Show comments section only if there are comments
      const commentsSection = document.getElementById('comments-section');
      if (comments && comments.trim() !== '') {
        commentsSection.style.display = 'flex';
        document.getElementById('modal-comments').textContent = comments;
      } else {
        commentsSection.style.display = 'none';
      }
    });
  });
});

    </script>

app/views/backlinks/index.html.erb
<%= render 'backlinks/link_table' %>

app/views/backlinks/new.html.erb
<div class="container mt-5" style="max-width: 800px;">
	<% if notice.present? %><div class="alert alert-success" style="margin-top:20px;"><%= notice %></div><% end %>
	 <% if @backlink.errors.any? %>
        <div class="alert alert-danger" style="border-radius: 10px;">
          <h5><strong>There were errors with your submission:</strong></h5>
          <ul>
            <% @backlink.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

  <div class="card shadow-sm" style="border-radius: 20px;">
    <div class="card-header text-white" style="background-color: #1A1364; border-top-left-radius: 20px; border-top-right-radius: 20px;">
      <h4 class="mb-0">Create a New Backlink</h4>
    </div>
    <div class="card-body">
      <%= form_with(model: @backlink, url: backlinks_path, method: :post, local: true, html: { class: 'needs-validation', novalidate: true }) do |form| %>

        <div class="mb-3">
          <%= form.label :site, class: 'form-label' do %>
            <strong>Site URL</strong>
          <% end %>
          <%= form.text_field :site, class: 'form-control', placeholder: 'Enter the site URL', required: true, autofocus: true %>
        </div>

        <div class="mb-3">
          <%= form.label :country, class: 'form-label' do %>
            <strong>Country</strong>
          <% end %>
          <%= form.select :country, options_for_select(@countries, prompt: 'Select a country'), {}, class: 'form-control', required: true %>
        </div>

        <div class="mb-3">
          <%= form.label :category, class: 'form-label' do %>
            <strong>Category</strong>
          <% end %>
          <%= form.select :category, options_for_select(@categories, prompt: 'Select a category'), {}, class: 'form-control', required: true %>
        </div>

        <div class="mb-3">
          <%= form.label :price, class: 'form-label' do %>
            <strong>Price (€)</strong>
          <% end %>
          <%= form.number_field :price, class: 'form-control', placeholder: 'Enter the price', step: '0.01', min: '0', required: true %>
        </div>

        <div class="mb-3">
          <%= form.label :domain_rank, class: 'form-label' do %>
            <strong>Domain Rank</strong>
          <% end %>
          <%= form.number_field :domain_rank, class: 'form-control', placeholder: 'Enter the domain rank', step: '1', min: '0', required: true %>
        </div>

        <div class="mb-3">
          <%= form.label :added_on, class: 'form-label' do %>
            <strong>Added On</strong>
          <% end %>
          <%= form.date_field :added_on, class: 'form-control', value: Date.today, required: true %>
        </div>

        <div class="mb-3">
          <%= form.label :duration, class: 'form-label' do %>
            <strong>Duration</strong>
          <% end %>
          <%= form.text_field :duration, class: 'form-control', placeholder: 'Enter the duration (e.g., 6 months)', required: true %>
        </div>

        <!-- Toggles Row -->
        <div class="row mb-3" style="padding-left:20px;">
          <div class="col-md-4">
            <div class="form-check form-switch">
              <%= form.check_box :article_writing, class: 'form-check-input', id: 'articleWritingSwitch' %>
              <%= form.label :article_writing, class: 'form-check-label', for: 'articleWritingSwitch' do %>
                <strong>Article Writing Included</strong>
              <% end %>
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-check form-switch">
              <%= form.check_box :cs_possible, class: 'form-check-input', id: 'csPossibleSwitch' %>
              <%= form.label :cs_possible, class: 'form-check-label', for: 'csPossibleSwitch' do %>
                <strong>C/S Possible</strong>
              <% end %>
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-check form-switch">
              <%= form.check_box :special_price, class: 'form-check-input', id: 'specialPriceSwitch' %>
              <%= form.label :special_price, class: 'form-check-label', for: 'specialPriceSwitch' do %>
                <strong>Special Price</strong>
              <% end %>
            </div>
          </div>
        </div>

        <div class="mb-3">
          <%= form.label :comments, class: 'form-label' do %>
            <strong>Additional Comments</strong>
          <% end %>
          <%= form.text_area :comments, class: 'form-control', placeholder: 'Enter any additional comments...', rows: 3 %>
        </div>

        <div class="text-center">
          <%= form.submit 'Create Backlink', class: 'btn btn-primary', style: 'border-radius: 20px; padding: 10px 20px;' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/backlinks/recently_deleted.html.erb
<h1>Recently Deleted</h1>

<% if @backlinks.any? %>
  <!-- Filtering Card -->

  
<!-- Backlinks Table Card -->
<div class="card" style="border-radius: 40px;">
  <div class="card-body table-responsive">
    <table class="table" id="backlinksTable">
      <thead>
        <tr>

          <th>Link Name</th>
          <th></th>
         
      </thead>
      <tbody>
        <% @backlinks.each do |backlink| %>
          <tr>
          	<td><%= clean_url(backlink.site) %></td> 
            <td name="<%= backlink.country %>"> <%= image_tag "#{backlink.country}.png", class: "flag-mini" %></td>
           <!-- Link Name Column -->
            
           
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% end %>

app/views/backlinks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @backlink %>

<div>
  <%= link_to "Edit this backlink", edit_backlink_path(@backlink) %> |
  <%= link_to "Back to backlinks", backlinks_path %>

  <%= button_to "Destroy this backlink", @backlink, method: :delete %>
</div>