config/routes.rb
Rails.application.routes.draw do
  root 'users#new'  # Root URL for user email input
  get '/login', to: 'sessions#new'  # Admin login page
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'
   get 'backlinks/by_country', to: 'backlinks#by_country', as: 'backlinks_by_country'
   get 'backlinks/by_category', to: 'backlinks#by_category', as: 'backlinks_by_category'
   get 'backlinks/by_new', to: 'backlinks#by_new', as: 'backlinks_by_new'
     get 'backlinks/by_special', to: 'backlinks#by_special', as: 'backlinks_by_special'
     get 'backlinks/recently_deleted', to: 'backlinks#recently_deleted', as: 'backlinks_recently_deleted'
  
  get '/admin/dashboard', to: 'admin#dashboard'  # Admin dashboard
  get 'backlinks/home', to: 'backlinks#home'

  resources :backlinks
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BacklinkExplorer</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'index','main','metisMenu.min', 'perfect-scrollbar', 'simplebar.min', 'data-turbolinks-track': 'reload' %>
   <%= javascript_include_tag 'jquery.min','bootstrap.bundle.min', 'data-turbolinks-track': 'reload' %>
   <%= stylesheet_link_tag 'simplebar', media: 'all' %>





  <!-- Bootstrap CSS CDN -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

  <!-- jQuery and Bootstrap JS CDN -->

  
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
<!-- Loading Spinner -->
<div id="loading-spinner" class="loading-spinner">
  <div class="spinner"></div>
</div>
  <% if session[:user_email].present? %>

   <div class="wrapper">

    <!--start sidebar -->
    <aside class="sidebar-wrapper" data-simplebar="true">
      <div class="sidebar-header">
        <div class="logo-box">
        
         <%= link_to image_tag('linkzenit.png', class: "logo-main"), backlinks_home_path %>
        </div>

        
      </div>
      <!--navigation-->
      <div>
      <ul class="metismenu" id="menu" >
         <li class="menu-label">What's Changed?</li>
        <li>
          <ul class="menu-section">

           
            <li> <%= link_to "Special Price", backlinks_by_special_path %>
                
            </li>
            <li> <%= link_to "Recently Added", backlinks_by_new_path %>
                
            </li>
            <li> <%= link_to "Recently Deleted", backlinks_recently_deleted_path %>
            </li>


           
            
          </ul>
        </li>
         <% if @countries.present? %>
        <li class="menu-label">Countries</li>
        <li>
          <ul class="menu-section">

            <% @countries.each do |country| %>
            <li> <a href="<%= backlinks_by_country_path(country: country) %>">
                <%= country %></a>
                
              </a>
            </li>
            <% end %>
            
          </ul>
        </li>
        <% end %>
        

        <li class="menu-label">Categories</li>
        <li>
          <ul class="menu-section">
            <% @categories.each do |category| %>
            <li> <a href="<%= backlinks_by_category_path(category: category) %>">
                <%= category %></a>
                
              </a>
            </li>
            <% end %>
            
          </ul>
        </li>
            
      </ul>
      <!--end navigation-->
    </aside>
    <!--end sidebar -->

    <!--start top header-->
    <header class="top-header">
      <nav class="navbar navbar-expand gap-3">
        <div class="toggle-icon">
          <ion-icon name="menu-outline"></ion-icon>
        </div>
       
        <form class="searchbar">
          <div class="position-absolute top-50 translate-middle-y search-icon ms-3">
            <ion-icon name="search-outline"></ion-icon>
          </div>
          <input class="form-control" type="text" placeholder="Search for anything">
          <div class="position-absolute top-50 translate-middle-y search-close-icon">
            <ion-icon name="close-outline"></ion-icon>
          </div>
        </form>
        <div class="top-navbar-right ms-auto">

          <ul class="navbar-nav align-items-center">
            
            <% if session[:admin] %>
            <li>
              
               
                <%= button_to('Admin Panel', admin_dashboard_path, method: :get, class: "btn btn-outline-light", style: "border-radius:20px; margin-left:10px;") %>
            
            </li>
             <li>
              
             
                <%= button_to('Add Link', new_backlink_path, method: :get, class: "btn btn-outline-light", style: "border-radius:20px; margin-left:10px;") %>
            
            </li>
            <li>
              
                 <%= button_to('Manage Access', users_path, method: :get, class: "btn btn-outline-light", style: "border-radius:20px; margin-left:10px;") %>
            
            </li>
            <li>
              <%= button_to('Logout', logout_path, method: :delete, data: { turbo_method: :delete }, class: "btn btn-outline-primary contact-btn", style: "border-radius:20px; margin-left:10px;") %>
            </li>
            <% else %>
            <li >
              
                <button class="btn btn-outline-primary contact-btn">Contact</button>
              </li>
             <li >
                <%= button_to('Logout', logout_path, method: :delete, data: { turbo_method: :delete }, class: "btn btn-outline-light", style: "border-radius:20px; margin-left:10px;") %>
                
            </li>
            

            <% end %>
            
              </ul>
            </li>

          </ul>

        </div>
      </nav>
    </header>
    <!--end top header-->


  
    <!-- start page content wrapper-->
    <div class="page-content-wrapper">
      <!-- start page content-->
   
      <div class ="content-area" style="padding:20px;">

      <%= yield %>
    </div>
    </div>


<!-- Modal Template -->

<% else %>
<%= yield %>
 <% end %>


<!-- jQuery from CDN -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Bootstrap JS from CDN -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
 

  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <!--plugins-->

  <script src="assets/plugins/apexcharts-bundle/js/apexcharts.min.js"></script>
  <script src="assets/plugins/easyPieChart/jquery.easypiechart.js"></script>
  <script src="assets/plugins/chartjs/chart.min.js"></script>

  



</body>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function () {
  // Hide the loading spinner when the page content is fully loaded
  const loadingSpinner = document.getElementById('loading-spinner');
  loadingSpinner.style.opacity = 1;
  setTimeout(() => {
    loadingSpinner.style.transition = 'opacity 0.5s';
    loadingSpinner.style.opacity = 0;
    setTimeout(() => loadingSpinner.style.display = 'none', 500); // Remove from DOM after fading out
  }, 200); // Small delay to ensure the spinner is visible before hiding
});
    $(function () {
    $('[data-toggle="tooltip"]').tooltip();
  });


</script>
</html>